In [1]:
import numpy as np

### 34.如何获取2016年七月的日期

In [4]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]') #起始时间，终止时间，参数类型
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35.怎样计算((A+B)*(-A/2))

In [8]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B) #out表示做完运算之后放在那里
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### 36.使用5种不同的方法从一个随机数组种提取整数

In [11]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[2.09701256 9.55098603 6.97778871 1.08458682 1.34133424 1.44175687
 6.41185545 5.08608744 5.2157643  8.187433  ]
[2. 9. 6. 1. 1. 1. 6. 5. 5. 8.]
[2. 9. 6. 1. 1. 1. 6. 5. 5. 8.]
[2. 9. 6. 1. 1. 1. 6. 5. 5. 8.]
[2 9 6 1 1 1 6 5 5 8]
[2. 9. 6. 1. 1. 1. 6. 5. 5. 8.]


### 37.建立一个5*5的行的值从0-4的矩阵

In [16]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38.考虑一个生成函数使其可以产生10个整数并能用这些整数建立一个数组

In [14]:
def generate():
    for x in range(10):
        yield x #yield相当于返回值
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39.建立一个长度为10的向量，并使它的值从0到1（不包括0和1）

In [17]:
Z = np.linspace(0, 1, 11, endpoint=False)[1:]
#起始点，结束点，元素个数，endpoint是否包含stop数值，retstep返回值形式，dtype数据类型
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40.建立一个随机的长度为10的向量并且排序

In [19]:
Z = np.random.random(10)
Z.sort()
print(Z)

[2.44273105e-04 1.14551622e-02 1.56970525e-01 3.80080478e-01
 5.56550968e-01 7.85460707e-01 8.99683470e-01 9.71783014e-01
 9.74631477e-01 9.86346773e-01]


### 41.怎样去求解一个小的数组的和比使用np.sum快呢

In [20]:
Z = np.arange(10)
np.add.reduce(Z)#np.add与np.add.reduce性能完全不同，reduce速度大概快两倍

45

### 42.怎样判断两个随机矩阵A和B是否相等

In [28]:
A = np.random.randint(0,2,5) #大小是0-1个数为5个
B = np.random.randint(0,2,5)
print(A)
print(B)
equal = np.allclose(A,B) #有一定的精读范围，差距很小也认为相同
print(equal)
equal = np.array_equal(A,B) #必须完全相等
print(equal)

[0 1 0 0 1]
[1 0 1 1 0]
False
False


### 43.使一个数组是不可移动的（只读）

In [34]:
Z = np.zeros(10)
Z.flags.writeable = False

### 44.考虑一个随机的10*2矩阵代表笛卡尔坐标系，转换它们到极坐标系

In [37]:
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2) 
T = np.arctan2(Y,X)
print(R,T)

[1.22583367 0.8362432  0.68024653 0.53806793 0.69933427 0.74318673
 0.74767802 0.53430566 1.2693079  0.43976847] [0.75216888 0.00908474 0.96566768 0.45999248 1.29053494 1.53394783
 0.90031644 1.23526899 0.68661771 1.24486751]


### 45.建立一个长度为10的随机向量并将最大值替换为0

In [38]:
Z = np.random.random(10)
Z[Z.argmax()] = 0 #Z的最大值位置
print(Z)

[0.00204205 0.45972604 0.06203617 0.85648688 0.35415382 0.02707247
 0.         0.25080414 0.18905212 0.79957646]


### 46.创建一个结构化数组，x和y坐标覆盖[0,1]x[0,1]区域

In [40]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47.将两个数组X,和Y，建立柯西矩阵C(Cij =1/(xi - yj))

In [42]:
X = np.arange(8)
Y = X+0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))
# 这里，我们输入X为：[0, 1, 2, 3, 4, 5, 6, 7], 输入Y为：[0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5
# np.substract.outer做的运算为
# [0-0,5, 0-1.5, 0-2.5, ..., 0-7.5]
# [1-0.5, 1-1.5, 1-2.5, ..., 1-7.5]
# ...
# [7-0.5, 7-1.5, 7-2.5, ..., 7-7.5]

3638.163637117973


### 48.打印出每一个numpy scalar type的最小和最大的代表值

In [43]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49.怎样打印一个数组中所有的值

In [51]:
np.set_printoptions(threshold=1000)#默认阈值就是1000
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 50.怎样去找到一个向量中最近的值

In [52]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

72


### 51.建立一个结构数组表示一个位置(x, y)和一种颜色(r, g, b)

In [53]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                   ('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])
                 ]
            )
#个数，[x,y]，[color]
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


D:\ruanjian\anaconda\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


### 52.从一个（100， 2）的随机向量中计算点到点之间的距离

In [54]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2 +(Y-Y.T)**2)
print(D)

[[0.         0.68344974 0.70794189 0.34411031 0.50544897 0.50915381
  0.77437118 1.05724705 0.26932728 0.95542414]
 [0.68344974 0.         0.16291855 0.64285167 0.25570226 0.20988158
  0.16637473 0.67568807 0.43165884 0.3331824 ]
 [0.70794189 0.16291855 0.         0.74176925 0.20828175 0.19980525
  0.07280875 0.83465833 0.43921878 0.45653964]
 [0.34411031 0.64285167 0.74176925 0.         0.59377664 0.562276
  0.78804387 0.7778703  0.41745303 0.80782499]
 [0.50544897 0.25570226 0.20828175 0.59377664 0.         0.05846591
  0.27949655 0.88629116 0.23636056 0.5883072 ]
 [0.50915381 0.20988158 0.19980525 0.562276   0.05846591 0.
  0.26525089 0.82802562 0.24194444 0.53916483]
 [0.77437118 0.16637473 0.07280875 0.78804387 0.27949655 0.26525089
  0.         0.81085993 0.50682538 0.40966751]
 [1.05724705 0.67568807 0.83465833 0.7778703  0.88629116 0.82802562
  0.81085993 0.         0.92928427 0.44666866]
 [0.26932728 0.43165884 0.43921878 0.41745303 0.23636056 0.24194444
  0.50682538 0.9292842

### 53.怎样将一个32bits的浮点型转换成一个32bits的整型

In [56]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)#type返回参数类型dtype返回数组参数类型astype对数据类型转换
print(Z)

[0 1 2 3 4 5 6 7 8 9]


### 54.怎样去读取下面的文件

In [58]:
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


### 55.什么是numpy数组的相等的枚举

In [65]:
Z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):#numpy中两种枚举方法
    print(index,value)
for index in np.ndindex(Z.shape):
    print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### 56.生成一个二维的高斯数组

In [67]:
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma,mu = 1.0,0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### 57.怎样在二维数组中随机放置p个元素

In [68]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 58.减去矩阵每一行的平均值

In [64]:
X = np.random.rand(5,10)
print(X)
Y = X-X.mean(axis=1,keepdims=True)#axis表示对列进行操作，keepdims表示对保持原维度，如果对列求平均那就保留列的信息
print(Y)

[[0.33551803 0.02735754 0.10825367 0.73685723 0.04808033 0.73456882
  0.12646175 0.70383805 0.98647337 0.34090811]
 [0.48068128 0.68960024 0.64156827 0.24616817 0.17783202 0.02122474
  0.7602651  0.54842985 0.2456494  0.53771131]
 [0.46960447 0.70857671 0.30072569 0.36225783 0.35763668 0.28812419
  0.87048151 0.43832991 0.85512416 0.48544751]
 [0.96090308 0.6946843  0.97881056 0.58589193 0.11291633 0.27362809
  0.67732111 0.79763117 0.43433181 0.52535599]
 [0.27265428 0.08559382 0.06465087 0.02572329 0.2086464  0.77175847
  0.59828438 0.10920981 0.24102253 0.88798043]]
[0.41483169 0.43491304 0.51363087 0.60414744 0.32655243]
[[-0.07931366 -0.38747415 -0.30657802  0.32202554 -0.36675136  0.31973713
  -0.28836994  0.28900636  0.57164168 -0.07392358]
 [ 0.04576824  0.2546872   0.20665523 -0.18874487 -0.25708102 -0.4136883
   0.32535206  0.11351681 -0.18926363  0.10279827]
 [-0.04402639  0.19494585 -0.21290518 -0.15137304 -0.15599419 -0.22550668
   0.35685065 -0.07530096  0.3414933  -0.028

### 59.怎样去根据第n列对一个数组排序

In [69]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 3 6]
 [9 8 9]
 [6 2 3]]
[[6 2 3]
 [9 3 6]
 [9 8 9]]


### 60.怎样判断一个2D的数组里面有空的列

In [70]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


### 61.从一个给定的数组中找到一个最近的值

In [71]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4375330716128135


### 62.怎样用iterator去计算两个（1,3）和（3,1）数组的和

In [72]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### 63.建立一个有列名的数组类

In [73]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10
