In [1]:
import numpy as np

### 64.给一个向量，如何吧这个向量中每个数字出现的次数加到1的向量中

In [10]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I,minlength=len(Z))
print(Z)
np.add.at(Z,I,1)  #另一种方法Z
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 3 1 3 3 4 3 7 6 0 9 7 2 0 8 1 2 1 6 0]
[5. 4. 3. 5. 2. 1. 3. 3. 2. 2.]
[9. 7. 5. 9. 3. 1. 5. 5. 3. 3.]


### 65.如何基于索引list I将向量X积累到F中

In [11]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)# I中没有0的索引，1的索引对应1+6=7……
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### 66.考虑(dtype=ubyte)的一个(w,h,3)图像，计算唯一颜色的数量

In [13]:
w,h = 16,16
I = np.random.randint(0,3,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1 2]


### 67.给一个四维的数组，如何一次性得到最后两轴的和

In [17]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

[[44 67 57 59]
 [54 53 60 74]
 [47 56 58 48]]


### 68.考虑一维向量D，如何使用描述子集指标的相同大小的向量S来计算D子集的均值?

In [19]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.43574287 0.37963426 0.43274742 0.55732245 0.5958436  0.62798399
 0.52058387 0.56743126 0.39928523 0.46653834]


### 69.如何得到点积的对角线?

In [20]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.5424624 , 0.27700532, 1.87243851, 0.5132117 , 0.45009462])

### 70.考虑向量[1,2,3,4,5]，如何在每个元素之间加3个0？

In [22]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### 71.一个维度是(5,5,3)的数组，如何让它和维度是(5,5)的数组相乘？

In [3]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


### 72.如何交换一个数组的两行

In [5]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]#交换第0行和第1行
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 73.一组描述10个三角形(具有共享顶点)的10个三元组，找到组成所有三角形的唯一线段集

In [14]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 63) ( 1, 64) ( 3, 42) ( 3, 60) ( 5, 60) ( 5, 92) ( 6, 88) ( 6, 98)
 (10, 42) (10, 66) (12, 64) (12, 81) (33, 43) (33, 93) (39, 39) (39, 58)
 (42, 60) (42, 66) (43, 93) (45, 94) (56, 85) (56, 96) (60, 92) (63, 64)
 (64, 81) (85, 96) (88, 98) (94, 94)]


### 74.给定一个数组C是一个bincount，如何产生一个数组，使np.bincount(a) == C?

In [17]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


### 75.如何用在一个数组上使用滑动窗口计算窗口的均值

In [20]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


### 76.考虑到一维数组Z，建立一个二维数组，要求第一行是z[0],z[1],z[2],第二行是z[-3],z[-2],z[-1]

In [21]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### 77.如何改变布尔类型，或者把他转变成浮点形式

In [2]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.99974748,  0.9264253 , -0.2129698 , -0.93922226,  0.10056406,
        0.59535095,  0.88138648, -0.52015814,  0.60318625,  0.84839648,
        0.09730616,  0.39342059, -0.91244371, -0.37348105, -0.58953174,
        0.19662582, -0.40291994,  0.30386482,  0.91457553, -0.32949151,
        0.63429508,  0.61714171,  0.41933412, -0.44714393, -0.76471348,
       -0.92260028,  0.15711737,  0.64314636, -0.43747522, -0.34377383,
        0.11585039,  0.35113974,  0.0259789 ,  0.86004279,  0.08413943,
        0.33873086, -0.62249493,  0.3276311 , -0.87400084,  0.51925435,
       -0.22362652,  0.64020401, -0.95232522,  0.48153759,  0.20879637,
       -0.51021778,  0.97608711, -0.05649598, -0.96097257,  0.46611125,
       -0.40832063,  0.17732084,  0.60390983, -0.91704894,  0.47049354,
       -0.58918556,  0.3534701 , -0.99100431,  0.70017366,  0.61622484,
        0.23126354, -0.529893  , -0.88987392,  0.9978758 ,  0.22271412,
       -0.54218952, -0.75835575, -0.86204723, -0.59703334, -0.25

### 78.给定一个二元组P0,P1描述直线和点p，如何计算p到直线上每个点的距离

In [3]:
def distance(p0,p1,p):
    T = p1 - p0
    L = (T**2).sum(axis=1)
    U = -((p0[:,0]-p[...,0])*T[:,0]+(p0[:,1]-p[...,1])*T[:,1]) / L //p[...;1]表示省略前面所有的冒号，只操作最后一维
    U = U.reshape(len(U),1)
    D = p0 + U*T - p 
    return np.sqrt((D**2).sum(axis=1))

p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))
print(distance(p0,p1,p))

[8.82071863 0.06200202 1.37348606 1.77854085 4.59690519 5.89584385
 6.02207435 0.55961262 1.55282881 0.29758883]


### 79.给定一个二元组P0,P1去定义一条线，如何计算每个点p[j]到线上每个点的距离

In [5]:
p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print(np.array([distance(p0,p1,p_i) for p_i in p]))

[[ 2.65880437  0.57977627  2.39123312  2.46226425  3.81517073  2.42512758
   5.39939928  3.34400762  0.07295486  4.89379296]
 [ 8.03233072  5.89233596  0.69079083  0.8347853   9.03936024  0.08719272
   5.69892796  1.57825851  1.23686551  6.63913187]
 [ 5.38868252  1.22431031  1.00857126  4.79588886  6.69625463  4.39001678
   8.47749027  0.24795493  2.47228352  2.61749247]
 [ 6.07756818  2.22340166 12.35748873  3.86682632  5.32325523  2.72672072
   3.39671572 13.03762258  7.08787958 11.03851065]
 [ 0.04221555  0.61529021  4.93734484  1.11356634  1.11745873  1.42766885
   3.27123575  6.1442597   1.63119768  6.1868287 ]
 [ 3.83518681  0.14828687  0.31542447  5.01521852  5.16788568  4.81536094
   8.15835572  1.71831248  2.55949346  2.36429207]
 [ 0.30329868  9.05352426  4.94790185 13.67399247  1.67647898 14.0030079
  14.78355491  4.11408203 10.80526715  6.39123176]
 [ 2.82630237  4.73367584  7.26143379  3.72402495  3.53718152  3.76815083
   0.27157325  4.3465187   6.19841504 11.08870943]
 

### 80.给定一个任意数组，编写一个函数去抽取一个固定形状和中心的子部分（必要时填充）

In [6]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 5 3 9 4 9 0 1 8 1]
 [5 7 6 2 5 6 0 2 7 9]
 [8 3 1 6 5 9 7 9 9 3]
 [7 6 0 6 0 4 4 3 9 9]
 [0 3 5 3 6 3 3 5 9 1]
 [3 9 7 3 0 5 3 6 9 0]
 [3 8 9 4 9 6 8 2 8 1]
 [2 8 0 9 8 1 4 9 7 5]
 [4 2 7 8 5 9 0 7 5 6]
 [1 5 4 6 0 7 1 8 9 1]]
[[0 0 0 0 0]
 [0 8 5 3 9]
 [0 5 7 6 2]
 [0 8 3 1 6]
 [0 7 6 0 6]]


D:\ruanjian\anaconda\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


### 81.给定一个16 * 1的数组，如何去把他们拆分成4 * 4的数组

In [11]:
Z = np.arange(1,15,dtype=np.uint32)

R = stride_tricks.as_strided(Z,(11,4),(4,4))

print(R)

NameError: name 'stride_tricks' is not defined

### 82.计算一个矩阵的秩

In [12]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


### 83.找到数列中出现最频繁的内容

In [14]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[0 0 1 8 2 9 9 3 3 2 3 7 4 5 5 6 6 7 0 9 2 3 6 2 2 8 2 6 3 9 4 8 1 4 8 6 9
 9 9 0 8 5 8 7 9 0 1 3 6 6]
9


### 84.从10 * 10维度的矩阵中抽取所有 3 * 3的矩阵

In [15]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1+(Z.shape[0]-3)
j = 1+(Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

NameError: name 'stride_tricks' is not defined

### 85.创建一个对称矩阵

In [18]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)//super指Symetric的父类，setitem指下标
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
print(S)
S[2,3] = 42
print(S)

[[ 3 16 14 13  9]
 [16  1  5  3 11]
 [14  5  0  5  7]
 [13  3  5  2  1]
 [ 9 11  7  1  9]]
[[ 3 16 14 13  9]
 [16  1  5  3 11]
 [14  5  0 42  7]
 [13  3 42  2  1]
 [ 9 11  7  1  9]]


### 86.给定p个形状为(n,n)的矩阵和p个形状为(n,1)的向量。如何一次计算p矩阵乘积的和?(结果有形状(n,1))

In [19]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


### 87.给定一个16 * 16的数组，如何去得到4 * 4的和

In [20]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


### 88.如何实现游戏的生活使用numpy数组?

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

### 89.如何找到数列中第n大的元素

In [21]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9996 9997 9995]


### 90.给定任意数量的向量，构建笛卡尔积(每个项的每个组合)

In [22]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


### 91.如何从常规数组创建记录数组?

In [23]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


### 92.给定一个大向量Z，用3种不同的方法计算Z的3次方

In [24]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.61 s ± 27.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
431 ms ± 7.95 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
271 ms ± 3.16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 93.考虑两个形状为(8,3)和(2,2)的数组A和B。如何找到A的行包含B的每一行的元素，而不考虑B中元素的顺序?

In [25]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 4 5 6]


### 94.给定一个10x3的矩阵，抽取值不相等的行

In [26]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 3 2]
 [4 0 1]
 [1 4 0]
 [2 3 2]
 [4 2 2]
 [0 4 2]
 [3 4 3]
 [4 1 3]
 [1 2 2]
 [1 0 3]]
[[2 3 2]
 [4 0 1]
 [1 4 0]
 [2 3 2]
 [4 2 2]
 [0 4 2]
 [3 4 3]
 [4 1 3]
 [1 2 2]
 [1 0 3]]
[[2 3 2]
 [4 0 1]
 [1 4 0]
 [2 3 2]
 [4 2 2]
 [0 4 2]
 [3 4 3]
 [4 1 3]
 [1 2 2]
 [1 0 3]]


### 95.将一个int向量用二进制矩阵表示

In [27]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


### 96.给定一个二维数组，如何去抽取唯一的一行

In [28]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]
[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]


### 97.考虑两个向量A和B，写出einsum等价于inner、outer、sum和mul函数

In [29]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.1132988 , 0.16471412, 0.14672436, 0.01675409, 0.0126167 ,
        0.13328967, 0.06236682, 0.04125773, 0.14297155, 0.06713004],
       [0.01437061, 0.02089204, 0.01861025, 0.00212506, 0.00160028,
        0.01690622, 0.00791049, 0.00523305, 0.01813425, 0.00851465],
       [0.49171289, 0.71485359, 0.63677864, 0.07271218, 0.05475604,
        0.57847255, 0.27066982, 0.17905712, 0.62049156, 0.29134204],
       [0.26066781, 0.37895959, 0.33757035, 0.03854632, 0.02902738,
        0.30666101, 0.14348802, 0.09492211, 0.32893621, 0.15444682],
       [0.50504035, 0.73422909, 0.65403798, 0.07468298, 0.05624015,
        0.59415156, 0.2780061 , 0.18391031, 0.63730946, 0.29923861],
       [0.3693352 , 0.53694055, 0.47829693, 0.05461554, 0.04112833,
        0.43450208, 0.20330541, 0.13449332, 0.46606339, 0.21883272],
       [0.02872291, 0.04175745, 0.03719678, 0.00424741, 0.00319852,
        0.03379089, 0.0158109 , 0.01045944, 0.03624539, 0.01701845],
       [0.01223747, 0.01779087, 0.0158477

### 98.考虑由两个向量(X,Y)描述的路径，如何使用等距样本进行采样

In [31]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

### 99.给定一个整数n和一个二维数组X，从X中选择可解释为n次多项式分布的行，即，只包含整数和n的行。

In [32]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


### 100.计算一个一维数组X的平均值的95%置信区间。，对数组中的元素重新采样N次，计算每个样本的平均值，然后计算平均值的百分比)。

In [33]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.15171281  0.21728253]
