# 100 numpy exercises（基础题目）

### 1.导入numpy模块

In [37]:
import numpy as np

### 2.输出numpy的版本和结构

In [4]:
print(np.__version__)
np.show_config()

1.17.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


### 3.创建一个10维的空向量

In [12]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.如何知道向量所占的空间

In [11]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


### 5.如何从numpy文档中获取

In [13]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


### 6.创造一个10维向量，切第五位数值为1

In [16]:
Z = np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7.创造一个表示10-49的向量

In [18]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8.翻转向量 

In [19]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 9.创造一个3x3并且从0-8的矩阵

In [21]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10.找到一个数组中非0元素的index

In [22]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


### 11.建立一个3*3的对角矩阵

In [23]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12.建立一个3*3*3的随机数数组

In [24]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.65031903 0.22141046 0.77738071]
  [0.9577254  0.47660869 0.1388305 ]
  [0.03544931 0.04649526 0.32257647]]

 [[0.57298043 0.47929077 0.16569894]
  [0.91331395 0.45096853 0.69030545]
  [0.09353521 0.27891017 0.56135664]]

 [[0.31267001 0.15259967 0.63550501]
  [0.56227136 0.21345272 0.62313052]
  [0.32265224 0.87651075 0.53432639]]]


### 13.建立一个10*10的随机数组，找到数组中的最大值和最小值

In [25]:
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()
print(Zmin,Zmax)

0.017917197910081395 0.9960444849936712


### 14.建立一个长度为30的随机向量，并打印出向量的平均值

In [27]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5294301038401517


### 15.建立一个二维数组使周边为1中心为0

In [29]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16.将一个全1的数组四周增加0

In [32]:
Z = np.ones((5,5))
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17.下面运行结果是什么

In [33]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1) #python无法对float类型判断相等，要用特定函数才行

nan
False
False
nan
True
False


### 18.建立一个5*5的矩阵，并让对角线下的值为1,2,3,4

In [35]:
Z = np.diag(1+np.arange(4),k=-1) #k为对角线位置，0为对角线，1为对角线上方，-1为对角线下方
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19.建立一个8*8的0和1间隔的矩阵

In [57]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1 #1：：2 从第一行开始：到最后一行：间隔为2
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20.在形状（6,7,8）的矩阵中，99这个数字所在的索引是多少

In [58]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


### 21.使用tile方法建立一个8*8的0和1间隔的矩阵

In [60]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22.标准化一个5*5的随机矩阵

In [56]:
Z = np.random.random((5,5))
Z = (Z-np.mean(Z))/np.std(Z)
print(Z)

[[-0.10283785  1.33448786 -1.26486611 -0.49602968 -0.80019106]
 [ 0.55124207 -0.92049617 -0.57777692  0.47172168 -0.69303457]
 [ 1.00230248 -0.13077409  1.6523009  -1.24022105 -1.27217765]
 [ 0.57713932  0.12236271 -1.23282868  1.1145903   1.46377628]
 [ 1.48513614 -1.1649162  -1.16737351  0.08847205  1.19999175]]


### 23.建立一个客户dtype用4bytes(RGBA)来描述一种颜色

In [69]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

D:\ruanjian\anaconda\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


### 24. 5 * 3的矩阵与3 * 2的矩阵做product

In [70]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

Z = np.ones((5,3))@np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 25.将一个一维的数组中元素在3-8之间的元素转换为负数

In [73]:
Z = np.arange(11)
Z[(3 < Z)&(Z <= 8)]*=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### 26.下面的代码的运行结果分别为什么

In [72]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


### 27.对于一个整数向量Z，下面哪一个表达式是合法的

In [ ]:
Z**Z #不合法
2<< Z >>2 #合法
Z <- Z #合法
1j*Z #合法
Z/1/1 #合法
Z<Z>Z #不合法

### 28.下面表达式的结果是什么

In [76]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0)) #" / "就一定表示 浮点数除法，返回浮点结果;" // "表示整数除法
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


D:\ruanjian\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\ruanjian\anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


### 29.如果将一个浮点数数组做四舍五入

In [78]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[ 3.68940471 -4.14771748  8.44947117 -7.02441452 -8.8969345   7.59485344
 -5.76393759 -6.99772811 -3.78153376  7.47649811]
[ 4. -5.  9. -8. -9.  8. -6. -7. -4.  8.]


### 30.找到两个数组中的相同的值

In [79]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2)) 

[1 3 4 5 7 8]


### 31.怎样去忽视所有的numpy的警告

In [80]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

### 32.下面的表达式是否正确

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1) #错误

### 33. 怎样去得到昨天，今天和明天的日期

In [82]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')